app:
  mongodb:
    uri: ${MONGODB_URI}
    cryptSharedLibPath: ${CRYPT_PATH}
    keyVaultNamespace: encryption.__keyVault
    encryptedDatabaseName: hrsystem
    encryptedCollectionName: employee
logging:
  level:
    org.springframework.data.mongodb: DEBUG